name: cd
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: build
        run: sudo docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/haskell-stack .
      -
        name: push
        run: sudo docker push ${{ secrets.DOCKER_HUB_USERNAME }}/haskell-stack